datasets:
    ALL:
        variables:
            rainfall: precip
            maximum_temperature: tmax
            minimum_temperature: tmin
            reference_evapotranspiration: et0
        daily:
            netcdf:
                precip: 
                    dir: /home/enacts/ENACTS_DATA/DATA/NETCDF/ALL/precip_daily
                    format: rr_mrg_%Y%m%d_ALL.nc
                    name: Daily rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: False
                tmax: 
                    dir: /home/enacts/ENACTS_DATA/DATA/NETCDF/ALL/tmax_daily
                    format: tmax_mrg_%Y%m%d_ALL.nc
                    name: Daily maximum temperature
                    varid: temp
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: False
                tmin: 
                    dir: /home/enacts/ENACTS_DATA/DATA/NETCDF/ALL/tmin_daily
                    format: tmin_mrg_%Y%m%d_ALL.nc
                    name: Daily minimum temperature
                    varid: temp
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: False
                et0: 
                    name: Daily reference evapotranspiration 
                    varid: et0
                    lon: lon
                    lat: lat
                    time: time
                    prec: float
                    units: mm
                    missval: -99
                    compute: True
                    data_type: et0
                    function: et0_hargreaves_modified
                    input_data: [tmax, tmin, precip]
                    # input_data: [tmax, tmin]
                    # function: et0_hargreaves_fao
                    input: daily
                    write_zarr: True
                    dir_zarr: et0_daily
            zarr_dir: /home/enacts/ENACTS_DATA/DATA/ZARR/ALL
            chunks:
                time: 1000
                lat: 50
                lon: 50
        dekadal:
            netcdf:
                precip: 
                    dir: /home/enacts/ENACTS_DATA/DATA/NETCDF/ALL/precip_dekad
                    format: rr_mrg_%Y%m%d_ALL.nc
                    name: Dekadal rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: False
                tmax: 
                    dir: /home/enacts/ENACTS_DATA/DATA/NETCDF/ALL/tmax_dekad
                    format: tmax_mrg_%Y%m%d_ALL.nc
                    name: Dekadal maximum temperature
                    varid: temp
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: False
                tmin: 
                    dir: /home/enacts/ENACTS_DATA/DATA/NETCDF/ALL/tmin_dekad
                    format: tmin_mrg_%Y%m%d_ALL.nc
                    name: Dekadal minimum temperature
                    varid: temp
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: False
            zarr_dir: /home/enacts/ENACTS_DATA/DATA/ZARR/ALL
            chunks:
                time: 1000
                lat: 50
                lon: 50
        monthly:
            netcdf:
                precip: 
                    name: Monthly rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: True
                    function: sum
                    input: dekadal
                    minfrac: 1
                tmax: 
                    name: Monthly maximum temperature
                    varid: tmax
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: True
                    function: mean
                    input: dekadal
                    minfrac: 1
                tmin: 
                    name: Monthly minimum temperature
                    varid: tmin
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: True
                    function: mean
                    input: dekadal
                    minfrac: 1
        seasonal:
            netcdf:
                precip: 
                    name: Seasonal rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: True
                    function: sum
                    input: dekadal
                    minfrac: 1
                tmax: 
                    name: Seasonal maximum temperature
                    varid: tmax
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: True
                    function: mean
                    input: dekadal
                    minfrac: 1
                tmin: 
                    name: Seasonal minimum temperature
                    varid: tmin
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: True
                    function: mean
                    input: dekadal
                    minfrac: 1
        annual:
            netcdf:
                precip: 
                    name: Annual rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: True
                    function: sum
                    input: dekadal
                    minfrac: 1
                tmax: 
                    name: Annual maximum temperature
                    varid: tmax
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: True
                    function: mean
                    input: dekadal
                    minfrac: 1
                tmin: 
                    name: Annual minimum temperature
                    varid: tmin
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: °C
                    missval: -99
                    compute: True
                    function: mean
                    input: dekadal
                    minfrac: 1
    MON:
        variables:
            rainfall: precip
        daily:
            netcdf:
                precip: 
                    dir: /home/enacts/ENACTS_DATA/DATA/NETCDF/ALL/precip_daily
                    format: rr_mrg_%Y%m%d_MON.nc
                    name: Daily rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: False
            zarr_dir: /home/enacts/ENACTS_DATA/DATA/ZARR/MON
            chunks:
                time: 1000
                lat: 50
                lon: 50
        dekadal:
            netcdf:
                precip: 
                    dir: /home/enacts/ENACTS_DATA/DATA/NETCDF/MON/precip_dekad
                    format: rr_mrg_%Y%m%d_MON.nc
                    name: Dekadal rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: False
            zarr_dir: /home/enacts/ENACTS_DATA/DATA/ZARR/MON
            chunks:
                time: 1000
                lat: 50
                lon: 50
        monthly:
            netcdf:
                precip: 
                    name: Monthly rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: True
                    function: sum
                    input: dekadal
                    minfrac: 1
        seasonal:
            netcdf:
                precip: 
                    name: Seasonal rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: True
                    function: sum
                    input: dekadal
                    minfrac: 1
        annual:
            netcdf:
                precip: 
                    name: Annual rainfall
                    varid: precip
                    lon: Lon
                    lat: Lat
                    time: Time
                    prec: float
                    units: mm
                    missval: -99
                    compute: True
                    function: sum
                    input: dekadal
                    minfrac: 1
climatology:
    zarr_dir: /home/enacts/ENACTS_DATA/DATA/ZARR/CLIM
